mutation CreateUser($name: String!, $email: String!) {
  createUser(data: { name: $name, email: $email }) {
    id
    name
    email
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(where: { id: $id }) {
    id
  }
}

mutation SetHeight($id: ID!, $height: Float!) {
  updateUser(
    where: {id: $id}
    data: {height: $height}
  ) {
    id
    height
  }
}

mutation SetAdmin($id: ID!, $isAdmin: Boolean!) {
  updateUser(
    where: {id: $id}
    data: {isAdmin: $isAdmin}
  ) {
    id
    isAdmin
  }
}
