subscription ReactToUserCreation {
	user(where: { mutation_in: CREATED }) {
		node {
	    name
	    email
			id
	  }
	}
}

subscription ReactToUserDeletion {
	user(where: { mutation_in: DELETED }) {
		previousValues {
	    name
	    email
			id
	  }
	}
}

subscription ReactToUserAdminChange {
	user(
		where: {
			AND: [
				{ mutation_in: UPDATED }
				{ updatedFields_contains: "isAdmin" }
			]
		}) {
		node {
			id
			isAdmin
	  }
	}
}
