query AllUsers {
  users {
    id
    name
    email
    isAdmin
  }
}

query GetUser($id: ID!) {
  user(where: { id: $id }) {
    id
    name
    email
    isAdmin
    height
  }
}

query Login($email: String!) {
  user(where: { email: $email }) {
    id
  }
}
