mutation CreateUser($name: String!, $email: String!) {
  createUser(data: { name: $name, email: $email }) {
    id
    name
    email
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(where: { id: $id }) {
    id
  }
}
